### ISSUE TITLE
No hardware description of video streaming solution

### ISSUE THREAD

**Issue by navderek** [emlid/Docs#6]
It's not clear...is the solution using a webcam connected to Raspberry Pi directly? Is it possible to connect FPV camera such as Fat Shark 600TVL model to the Navio+ board and still perform streaming from the Raspberry Pi 2?

The document needs to elaborate on exactly how the video streaming is achieved hardware wise.

**Comment by ivereninov** [comment]
The tutorial covers Raspberry Pi camera, it is a good point that it is not stated there.  You can not connect analog video cameras as there is no analog video input on RPi, but you can use USB or CSI cameras.
