### ISSUE TITLE
Failed to fetch on install of gstreamer

### ISSUE THREAD

**Issue by navderek** [emlid/Docs#7]
pasting output after entering command from EMLID doc:

^Cpi@navio-rpi ~ $ sudo apt-get install gstreamer1.0-plugins-good gstreamer1.0-pgins-bad gstreamer1.0-libav
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  dconf-gsettings-backend dconf-service fontconfig fontconfig-config freepats
  glib-networking glib-networking-common glib-networking-services
  gsettings-desktop-schemas gstreamer1.0-x hicolor-icon-theme libaa1 libass4
  libasyncns0 libatk1.0-0 libatk1.0-data libavahi-client3 libavahi-common-data
  libavahi-common3 libavc1394-0 libavcodec53 libavcodec54 libavformat54
  libavutil51 libavutil52 libcaca0 libcairo-gobject2 libcairo2 libchromaprint0
  libcups2 libdatrie1 libdc1394-22 libdca0 libdconf0 libdirac-encoder0 libdv4
  libdvdnav4 libdvdread4 libenca0 libfaad2 libfftw3-3 libflac8 libflite1
  libfluidsynth1 libfontconfig1 libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-common
  libgme0 libgraphite2-2.0.0 libgsm1 libgtk2.0-0 libgtk2.0-bin
  libgtk2.0-common libharfbuzz0a libice6 libiec61883-0 libilmbase6
  libjack-jackd2-0 libjasper1 libjson0 libkate1 libmimic0 libmms0 libmodplug1
  libmozjs10d libmp3lame0 libmpg123-0 libnspr4 libofa0 libopenal-data
  libopenal1 libopencore-amrnb0 libopencore-amrwb0 libopencv-calib3d2.4
  libopencv-contrib2.4 libopencv-core2.4 libopencv-features2d2.4
  libopencv-flann2.4 libopencv-highgui2.4 libopencv-imgproc2.4
  libopencv-legacy2.4 libopencv-ml2.4 libopencv-objdetect2.4
  libopencv-photo2.4 libopencv-stitching2.4 libopencv-ts2.4 libopencv-video2.4
  libopencv-videostab2.4 libopenexr6 libopenjpeg2 libopus0 libpango-1.0-0
  libpango1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libpangox-1.0-0
  libpangoxft-1.0-0 libpixman-1-0 libproxy0 libpulse0 libraw1394-11 libsbc1
  libschroedinger-1.0-0 libshout3 libsm6 libsndfile1 libsoundtouch0
  libsoup2.4-1 libspandsp2 libspeex1 libsrtp0 libswscale2 libtag1-vanilla
  libtag1c2a libthai-data libthai0 libtiff4 libva1 libvo-aacenc0
  libvo-amrwbenc0 libvpx1 libwavpack1 libwildmidi-config libwildmidi1 libx11-6
  libx11-data libx11-xcb1 libx264-123 libx264-130 libxau6 libxcb-render0
  libxcb-shm0 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxdmcp6
  libxext6 libxfixes3 libxft2 libxi6 libxinerama1 libxml2 libxrandr2
  libxrender1 libxtst6 libxv1 libxvidcore4 libzbar0 sgml-base shared-mime-info
  ttf-dejavu-core x11-common xml-core
Suggested packages:
  frei0r-plugins libchromaprint-tools python-acoustid cups-common libdv-bin
  oss-compat libdvdcss2 libfftw3-bin libfftw3-dev librsvg2-common gvfs jackd2
  libjasper-runtime libportaudio2 libroar-compat2 opus-tools ttf-baekmuk
  ttf-arphic-gbsn00lp ttf-arphic-bsmi00lp ttf-arphic-gkai00mp
  ttf-arphic-bkai00mp pulseaudio libraw1394-doc speex srtp-utils sgml-base-doc
  debhelper
The following NEW packages will be installed:
  dconf-gsettings-backend dconf-service fontconfig fontconfig-config freepats
  glib-networking glib-networking-common glib-networking-services
  gsettings-desktop-schemas gstreamer1.0-libav gstreamer1.0-plugins-bad
  gstreamer1.0-plugins-good gstreamer1.0-x hicolor-icon-theme libaa1 libass4
  libasyncns0 libatk1.0-0 libatk1.0-data libavahi-client3 libavahi-common-data
  libavahi-common3 libavc1394-0 libavcodec53 libavcodec54 libavformat54
  libavutil51 libavutil52 libcaca0 libcairo-gobject2 libcairo2 libchromaprint0
  libcups2 libdatrie1 libdc1394-22 libdca0 libdconf0 libdirac-encoder0 libdv4
  libdvdnav4 libdvdread4 libenca0 libfaad2 libfftw3-3 libflac8 libflite1
  libfluidsynth1 libfontconfig1 libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-common
  libgme0 libgraphite2-2.0.0 libgsm1 libgtk2.0-0 libgtk2.0-bin
  libgtk2.0-common libharfbuzz0a libice6 libiec61883-0 libilmbase6
  libjack-jackd2-0 libjasper1 libjson0 libkate1 libmimic0 libmms0 libmodplug1
  libmozjs10d libmp3lame0 libmpg123-0 libnspr4 libofa0 libopenal-data
  libopenal1 libopencore-amrnb0 libopencore-amrwb0 libopencv-calib3d2.4
  libopencv-contrib2.4 libopencv-core2.4 libopencv-features2d2.4
  libopencv-flann2.4 libopencv-highgui2.4 libopencv-imgproc2.4
  libopencv-legacy2.4 libopencv-ml2.4 libopencv-objdetect2.4
  libopencv-photo2.4 libopencv-stitching2.4 libopencv-ts2.4 libopencv-video2.4
  libopencv-videostab2.4 libopenexr6 libopenjpeg2 libopus0 libpango-1.0-0
  libpango1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libpangox-1.0-0
  libpangoxft-1.0-0 libpixman-1-0 libproxy0 libpulse0 libraw1394-11 libsbc1
  libschroedinger-1.0-0 libshout3 libsm6 libsndfile1 libsoundtouch0
  libsoup2.4-1 libspandsp2 libspeex1 libsrtp0 libswscale2 libtag1-vanilla
  libtag1c2a libthai-data libthai0 libtiff4 libva1 libvo-aacenc0
  libvo-amrwbenc0 libvpx1 libwavpack1 libwildmidi-config libwildmidi1 libx11-6
  libx11-data libx11-xcb1 libx264-123 libx264-130 libxau6 libxcb-render0
  libxcb-shm0 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxdmcp6
  libxext6 libxfixes3 libxft2 libxi6 libxinerama1 libxml2 libxrandr2
  libxrender1 libxtst6 libxv1 libxvidcore4 libzbar0 sgml-base shared-mime-info
  ttf-dejavu-core x11-common xml-core
0 upgraded, 157 newly installed, 0 to remove and 0 not upgraded.
Need to get 84.9 MB of archives.
After this operation, 182 MB of additional disk space will be used.
Do you want to continue [Y/n]? y
Get:1 http://archive.raspberrypi.org/debian/ wheezy/main libatk1.0-data all 2.8.0-2rpi2 [168 kB]
Err http://mirrordirector.raspbian.org/raspbian/ wheezy/main libxml2 armhf 2.8.0+dfsg1-7+wheezy3
  404  Not Found
Get:2 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libxau6 armhf 1:1.0.7-1 [17.6 kB]
Get:3 http://archive.raspberrypi.org/debian/ wheezy/main libatk1.0-0 armhf 2.8.0-2rpi2 [78.5 kB]
Get:4 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libxdmcp6 armhf 1:1.1.1-1 [24.6 kB]
Get:5 http://archive.raspberrypi.org/debian/ wheezy/main libavutil52 armhf 6:9.14-1rpi1rpi1 [131 kB]
Get:6 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libxcb1 armhf 1.8.1-2+deb7u1 [42.8 kB]
Err http://mirrordirector.raspbian.org/raspbian/ wheezy/main libx11-data all 2:1.5.0-1+deb7u1+wheezy
  404  Not Found
Err http://mirrordirector.raspbian.org/raspbian/ wheezy/main libx11-6 armhf 2:1.5.0-1+deb7u1+wheezy
  404  Not Found
Get:7 http://archive.raspberrypi.org/debian/ wheezy/main libopus0 armhf 1.1~beta-3rpi2 [159 kB]
Get:8 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libaa1 armhf 1.4p5-40 [59.3 kB]
Get:9 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libasyncns0 armhf 0.8-4 [12.8 kB]
Get:10 http://archive.raspberrypi.org/debian/ wheezy/main libx264-130 armhf 2:0.130.2282+git1db4621-2rpi1rpi2 [1372 kB]
Get:11 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libavahi-common-data armhf 0.6.31-2 [137 kB]
Get:12 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libavahi-common3 armhf 0.6.31-2 [52.6 kB]
Get:13 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libavahi-client3 armhf 0.6.31-2 [55.4 kB]
Get:14 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libraw1394-11 armhf 2.0.9-1 [45.0 kB]
Get:15 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libavc1394-0 armhf 0.5.4-2 [21.8 kB]
Get:16 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libavutil51 armhf 6:0.8.17-1+rpi1 [102 kB]
Get:17 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libdirac-encoder0 armhf 1.0.2-6 [350 kB]
Get:18 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libgsm1 armhf 1.0.13-4 [30.9 kB]
Get:19 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libmp3lame0 armhf 3.99.5+repack1-3 [384 kB]
Get:20 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libopenjpeg2 armhf 1.3+dfsg-4.8 [76.2 kB]
Get:21 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libschroedinger-1.0-0 armhf 1.0.11-2 [299 kB]
Get:22 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libspeex1 armhf 1.2~rc1-7 [61.7 kB]
Get:23 http://archive.raspberrypi.org/debian/ wheezy/main libavcodec54 armhf 6:9.14-1rpi1rpi1 [3599 kB]
Get:24 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libva1 armhf 1.0.15-4 [35.8 kB]
Get:25 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libvpx1 armhf 1.1.0-1+rpi1 [201 kB]
Get:26 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libx264-123 armhf 2:0.123.2189+git35cf912-1+rpi1 [456 kB]
Get:27 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libxvidcore4 armhf 2:1.3.2-9 [311 kB]
Err http://mirrordirector.raspbian.org/raspbian/ wheezy/main libxrender1 armhf 1:0.9.7-1+deb7u1
  404  Not Found
Err http://mirrordirector.raspbian.org/raspbian/ wheezy/main libcups2 armhf 1.5.3-5+deb7u5
  404  Not Found
Get:28 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libavcodec53 armhf 6:0.8.17-1+rpi1 [2306 kB]
Err http://mirrordirector.raspbian.org/raspbian/ wheezy/main libx11-xcb1 armhf 2:1.5.0-1+deb7u1+wheezy
  404  Not Found
Get:29 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libopencore-amrnb0 armhf 0.1.3-2 [94.6 kB]
Get:30 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libopencore-amrwb0 armhf 0.1.3-2 [48.0 kB]
Get:31 http://archive.raspberrypi.org/debian/ wheezy/main libavformat54 armhf 6:9.14-1rpi1rpi1 [683 kB]
Get:32 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libvo-aacenc0 armhf 0.1.2-1 [70.7 kB]
Get:33 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libvo-amrwbenc0 armhf 0.1.2-1 [67.1 kB]
Get:34 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libcaca0 armhf 0.99.beta18-1 [383 kB]
Get:35 http://mirrordirector.raspbian.org/raspbian/ wheezy/main ttf-dejavu-core all 2.33-3 [1021 kB]
Get:36 http://archive.raspberrypi.org/debian/ wheezy/main libpixman-1-0 armhf 0.33.1+git20140627-c37ff5-rpi2rpi1 [177 kB]
Get:37 http://mirrordirector.raspbian.org/raspbian/ wheezy/main fontconfig-config all 2.9.0-7.1 [233 kB]
Get:38 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libfontconfig1 armhf 2.9.0-7.1 [285 kB]
Get:39 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libxcb-render0 armhf 1.8.1-2+deb7u1 [16.4 kB]
Get:40 http://archive.raspberrypi.org/debian/ wheezy/main libcairo2 armhf 1.12.16-rpi1rpi2 [968 kB]
Get:41 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libxcb-shm0 armhf 1.8.1-2+deb7u1 [10.0 kB]
Get:42 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libxext6 armhf 2:1.3.1-2+deb7u1 [48.7 kB]
Get:43 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libchromaprint0 armhf 0.6-2 [28.5 kB]
Get:44 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libdatrie1 armhf 0.2.5-3 [26.0 kB]
Get:45 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libdconf0 armhf 0.12.1-3 [21.0 kB]
Get:46 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libdv4 armhf 1.0.0-6 [76.6 kB]
Get:47 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libdvdread4 armhf 4.2.0+20120521-2 [55.2 kB]
Get:48 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libdvdnav4 armhf 4.2.0+20120524-2 [42.2 kB]
Get:49 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libfaad2 armhf 2.7-8 [177 kB]
Get:50 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libfftw3-3 armhf 3.3.2-3.1 [1156 kB]
Get:51 http://archive.raspberrypi.org/debian/ wheezy/main libcairo-gobject2 armhf 1.12.16-rpi1rpi2 [540 kB]
Get:52 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libflac8 armhf 1.2.1-6+deb7u1 [144 kB]
Get:53 http://mirrordirector.raspbian.org/raspbian/ wheezy/main x11-common all 1:7.7+3~deb7u1 [284 kB]
Get:54 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libice6 armhf 2:1.0.8-2 [56.2 kB]
Get:55 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libjson0 armhf 0.10-1.2 [22.1 kB]
Get:56 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libsm6 armhf 2:1.2.1-2 [32.5 kB]
Get:57 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libsndfile1 armhf 1.0.25-5 [249 kB]
Get:58 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libxi6 armhf 2:1.6.1-1+deb7u1 [71.3 kB]
Get:59 http://archive.raspberrypi.org/debian/ wheezy/main libjack-jackd2-0 armhf 1.9.8~dfsg.4+20120529git007cdc37-5+rpi2 [185 kB]
Get:60 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libxtst6 armhf 2:1.2.1-1+deb7u1 [25.2 kB]
Get:61 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libpulse0 armhf 2.0-6.1 [196 kB]
Get:62 http://archive.raspberrypi.org/debian/ wheezy/main libgdk-pixbuf2.0-common all 2.28.2-1rpi4rpi1 [292 kB]
Get:63 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libfluidsynth1 armhf 1.1.5-2 [167 kB]
Get:64 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libjasper1 armhf 1.900.1-13+deb7u3 [142 kB]
Get:65 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libtiff4 armhf 3.9.6-11 [188 kB]
Get:66 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libgtk2.0-common all 2.24.10-2 [3081 kB]
Get:67 http://archive.raspberrypi.org/debian/ wheezy/main libgdk-pixbuf2.0-0 armhf 2.28.2-1rpi4rpi1 [141 kB]
Get:68 http://archive.raspberrypi.org/debian/ wheezy/main libpango-1.0-0 armhf 1.32.5-5rpi3 [247 kB]
Get:69 http://archive.raspberrypi.org/debian/ wheezy/main libharfbuzz0a armhf 0.9.19-1co2rpi2 [433 kB]
Get:70 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libthai-data all 0.1.18-2 [154 kB]
Get:71 http://archive.raspberrypi.org/debian/ wheezy/main libpangoft2-1.0-0 armhf 1.32.5-5rpi3 [181 kB]
Get:72 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libthai0 armhf 0.1.18-2 [39.7 kB]
Get:73 http://mirrordirector.raspbian.org/raspbian/ wheezy/main fontconfig armhf 2.9.0-7.1 [348 kB]
Get:74 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libgraphite2-2.0.0 armhf 1.1.3-1 [52.5 kB]
Get:75 http://archive.raspberrypi.org/debian/ wheezy/main libpangocairo-1.0-0 armhf 1.32.5-5rpi3 [171 kB]
Get:76 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libxft2 armhf 2.3.1-1 [55.4 kB]
Get:77 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libxcomposite1 armhf 1:0.4.3-2 [16.2 kB]
Get:78 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libxfixes3 armhf 1:5.0-4+deb7u1 [19.5 kB]
Get:79 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libxcursor1 armhf 1:1.1.13-1+deb7u1 [23.8 kB]
Get:80 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libxdamage1 armhf 1:1.1.3-2 [13.8 kB]
Get:81 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libxinerama1 armhf 2:1.1.2-1+deb7u1 [16.2 kB]
Get:82 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libxrandr2 armhf 2:1.3.2-2+deb7u1 [30.2 kB]
Get:83 http://archive.raspberrypi.org/debian/ wheezy/main libpangoxft-1.0-0 armhf 1.32.5-5rpi3 [167 kB]
Get:84 http://mirrordirector.raspbian.org/raspbian/ wheezy/main shared-mime-info armhf 1.0-1 [1065 kB]
Get:85 http://archive.raspberrypi.org/debian/ wheezy/main libpangox-1.0-0 armhf 0.0.2-4rpi2 [38.2 kB]
Get:86 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libgtk2.0-0 armhf 2.24.10-2 [1893 kB]
Get:87 http://archive.raspberrypi.org/debian/ wheezy/main libpango1.0-0 armhf 1.32.5-5rpi3 [158 kB]
Get:88 http://archive.raspberrypi.org/debian/ wheezy/main glib-networking-common all 2.36.1-2+rpi1rpi3 [49.0 kB]
Get:89 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libmms0 armhf 0.6.2-3+deb7u1 [43.3 kB]
Get:90 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libmpg123-0 armhf 1.14.4-1 [173 kB]
Get:91 http://archive.raspberrypi.org/debian/ wheezy/main glib-networking-services armhf 2.36.1-2+rpi1rpi3 [13.8 kB]
Get:92 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libnspr4 armhf 2:4.9.2-1+deb7u2 [117 kB]
Get:93 http://archive.raspberrypi.org/debian/ wheezy/main glib-networking armhf 2.36.1-2+rpi1rpi3 [39.2 kB]
Get:94 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libopenal-data all 1:1.14-4 [11.1 kB]
Get:95 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libopenal1 armhf 1:1.14-4 [177 kB]
Get:96 http://archive.raspberrypi.org/debian/ wheezy/main libsoup2.4-1 armhf 2.42.2-6rpi2 [202 kB]
Get:97 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libproxy0 armhf 0.3.1-6 [30.0 kB]
Get:98 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libshout3 armhf 2.2.2-8 [37.2 kB]
Get:99 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libsoundtouch0 armhf 1.6.0-3 [37.6 kB]
Get:100 http://mirrordirector.raspbian.org/raspbian/ wheezy/main dconf-service armhf 0.12.1-3 [20.2 kB]
Get:101 http://mirrordirector.raspbian.org/raspbian/ wheezy/main dconf-gsettings-backend armhf 0.12.1-3 [18.4 kB]
Get:102 http://mirrordirector.raspbian.org/raspbian/ wheezy/main gsettings-desktop-schemas all 3.4.2-3 [114 kB]
Get:103 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libtag1-vanilla armhf 1.7.2-1 [210 kB]
Get:104 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libwavpack1 armhf 4.60.1-3 [80.3 kB]
Get:105 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libwildmidi-config all 0.2.3.4-2.1 [15.9 kB]
Get:106 http://archive.raspberrypi.org/debian/ wheezy/main libswscale2 armhf 6:9.14-1rpi1rpi1 [147 kB]
Get:107 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libwildmidi1 armhf 0.2.3.4-2.1 [69.3 kB]
Get:108 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libxv1 armhf 2:1.0.7-1+deb7u1 [20.4 kB]
Get:109 http://mirrordirector.raspbian.org/raspbian/ wheezy/main sgml-base all 1.26+nmu4 [14.6 kB]
Get:110 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libenca0 armhf 1.13-4 [67.5 kB]
Get:111 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libass4 armhf 0.10.0-3 [56.8 kB]
Get:112 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libdca0 armhf 0.0.5-5 [112 kB]
Get:113 http://archive.raspberrypi.org/debian/ wheezy/main libopencv-core2.4 armhf 2.4.1+dfsg-0exp2rpi2 [773 kB]
Get:114 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libflite1 armhf 1.4-release-6 [12.8 MB]
Get:115 http://archive.raspberrypi.org/debian/ wheezy/main libopencv-flann2.4 armhf 2.4.1+dfsg-0exp2rpi2 [124 kB]
Get:116 http://archive.raspberrypi.org/debian/ wheezy/main libopencv-imgproc2.4 armhf 2.4.1+dfsg-0exp2rpi2 [670 kB]
Get:117 http://archive.raspberrypi.org/debian/ wheezy/main libopencv-features2d2.4 armhf 2.4.1+dfsg-0exp2rpi2 [216 kB]
Get:118 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libgme0 armhf 0.5.5-2 [127 kB]
Get:119 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libkate1 armhf 0.4.1-1 [39.9 kB]
Get:120 http://archive.raspberrypi.org/debian/ wheezy/main libopencv-calib3d2.4 armhf 2.4.1+dfsg-0exp2rpi2 [255 kB]
Get:121 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libmimic0 armhf 1.0.4-2.1 [19.6 kB]
Get:122 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libmodplug1 armhf 1:0.8.8.4-3+deb7u1+git20130828 [180 kB]
Get:123 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libofa0 armhf 0.9.3-5 [54.8 kB]
Get:124 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libdc1394-22 armhf 2.2.0-2 [116 kB]
Get:125 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libilmbase6 armhf 1.0.1-4 [119 kB]
Get:126 http://archive.raspberrypi.org/debian/ wheezy/main libopencv-highgui2.4 armhf 2.4.1+dfsg-0exp2rpi2 [116 kB]
Get:127 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libopenexr6 armhf 1.6.1-6 [227 kB]
Get:128 http://archive.raspberrypi.org/debian/ wheezy/main libopencv-ml2.4 armhf 2.4.1+dfsg-0exp2rpi2 [231 kB]
Get:129 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libspandsp2 armhf 0.0.6~pre20-3.1 [276 kB]
Get:130 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libsrtp0 armhf 1.4.4+20100615~dfsg-2+deb7u1 [76.6 kB]
Get:131 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libzbar0 armhf 0.10+doc-8 [98.3 kB]
Get:132 http://mirrordirector.raspbian.org/raspbian/ wheezy/main freepats all 20060219-1 [29.0 MB]
Get:133 http://archive.raspberrypi.org/debian/ wheezy/main libopencv-objdetect2.4 armhf 2.4.1+dfsg-0exp2rpi2 [215 kB]
Get:134 http://archive.raspberrypi.org/debian/ wheezy/main libopencv-video2.4 armhf 2.4.1+dfsg-0exp2rpi2 [92.7 kB]
Get:135 http://archive.raspberrypi.org/debian/ wheezy/main libopencv-contrib2.4 armhf 2.4.1+dfsg-0exp2rpi2 [294 kB]
Get:136 http://archive.raspberrypi.org/debian/ wheezy/main libopencv-legacy2.4 armhf 2.4.1+dfsg-0exp2rpi2 [493 kB]
Get:137 http://archive.raspberrypi.org/debian/ wheezy/main libopencv-photo2.4 armhf 2.4.1+dfsg-0exp2rpi2 [25.6 kB]
Get:138 http://archive.raspberrypi.org/debian/ wheezy/main libopencv-stitching2.4 armhf 2.4.1+dfsg-0exp2rpi2 [155 kB]
Get:139 http://archive.raspberrypi.org/debian/ wheezy/main libopencv-ts2.4 armhf 2.4.1+dfsg-0exp2rpi2 [223 kB]
Get:140 http://archive.raspberrypi.org/debian/ wheezy/main libopencv-videostab2.4 armhf 2.4.1+dfsg-0exp2rpi2 [92.6 kB]
Get:141 http://archive.raspberrypi.org/debian/ wheezy/main libsbc1 armhf 1.1-1rpi2 [38.1 kB]
Get:142 http://archive.raspberrypi.org/debian/ wheezy/main gstreamer1.0-plugins-bad armhf 1.2.1-0+rpi1rpi3 [1878 kB]
Get:143 http://archive.raspberrypi.org/debian/ wheezy/main gstreamer1.0-libav armhf 1.2.0-1co2rpi1rpi3 [160 kB]
Get:144 http://archive.raspberrypi.org/debian/ wheezy/main gstreamer1.0-plugins-good armhf 1.2.0-1co6rpi3 [2048 kB]
Get:145 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libiec61883-0 armhf 1.2.0-0.1 [33.5 kB]
Get:146 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libtag1c2a armhf 1.7.2-1 [9332 B]
Get:147 http://mirrordirector.raspbian.org/raspbian/ wheezy/main hicolor-icon-theme all 0.12-1 [11.7 kB]
Get:148 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libgtk2.0-bin armhf 2.24.10-2 [477 kB]
Get:149 http://archive.raspberrypi.org/debian/ wheezy/main gstreamer1.0-x armhf 1.2.0-1co1rpi3 [775 kB]
Get:150 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libmozjs10d armhf 10.0.12esr-1+rpi2 [998 kB]
Get:151 http://mirrordirector.raspbian.org/raspbian/ wheezy/main xml-core all 0.13+nmu2 [24.2 kB]
Fetched 82.6 MB in 1min 10s (1165 kB/s)
Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/libx/libxml2/libxml2_2.8.0+dfsg1-7+wheezy3_armhf.deb  404  Not Found
Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/libx/libx11/libx11-data_1.5.0-1+deb7u1+wheezy_all.deb  404  Not Found
Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/libx/libx11/libx11-6_1.5.0-1+deb7u1+wheezy_armhf.deb  404  Not Found
Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/libx/libxrender/libxrender1_0.9.7-1+deb7u1_armhf.deb  404  Not Found
Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/c/cups/libcups2_1.5.3-5+deb7u5_armhf.deb  404  Not Found
Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/libx/libx11/libx11-xcb1_1.5.0-1+deb7u1+wheezy_armhf.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by Clouded** [comment]
What distributive do you use?

**Comment by navderek** [comment]
I was just following exact instructions from EMLID doc...anyways I followed some instructions elsewhere (from UAV Matrix blog) and things are working now. It's too bad we cannot just have a simple image to download, or like someone suggested a pre-made script that just works. It would help make better adoption.

**Comment by staroselskii** [comment]
@navderek 

I'm closing the issue. Please, use our [forum](http://community.emlid.com) if you encounter problems like this one.
